    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_list: fo,wee
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-10.el7.x86_64.rpm
        curl -L -O https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-10.el7.x86_64.rpm
        rpm -U --quiet p7zip-16.02-10.el7.x86_64.rpm
        rpm -U --quiet p7zip-plugins-16.02-10.el7.x86_64.rpm
